package it.formazione.libreria.mybatis.model;

public class CasaEditrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casa_editrice.id
     *
     * @mbg.generated Tue Nov 07 17:49:16 CET 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column casa_editrice.nome_casa
     *
     * @mbg.generated Tue Nov 07 17:49:16 CET 2023
     */
    private String nomeCasa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casa_editrice.id
     *
     * @return the value of casa_editrice.id
     *
     * @mbg.generated Tue Nov 07 17:49:16 CET 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casa_editrice.id
     *
     * @param id the value for casa_editrice.id
     *
     * @mbg.generated Tue Nov 07 17:49:16 CET 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column casa_editrice.nome_casa
     *
     * @return the value of casa_editrice.nome_casa
     *
     * @mbg.generated Tue Nov 07 17:49:16 CET 2023
     */
    public String getNomeCasa() {
        return nomeCasa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column casa_editrice.nome_casa
     *
     * @param nomeCasa the value for casa_editrice.nome_casa
     *
     * @mbg.generated Tue Nov 07 17:49:16 CET 2023
     */
    public void setNomeCasa(String nomeCasa) {
        this.nomeCasa = nomeCasa;
    }
}