package it.formazione.libreria.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class LibriExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public LibriExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNomeIsNull() {
            addCriterion("nome is null");
            return (Criteria) this;
        }

        public Criteria andNomeIsNotNull() {
            addCriterion("nome is not null");
            return (Criteria) this;
        }

        public Criteria andNomeEqualTo(String value) {
            addCriterion("nome =", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotEqualTo(String value) {
            addCriterion("nome <>", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeGreaterThan(String value) {
            addCriterion("nome >", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeGreaterThanOrEqualTo(String value) {
            addCriterion("nome >=", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeLessThan(String value) {
            addCriterion("nome <", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeLessThanOrEqualTo(String value) {
            addCriterion("nome <=", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeLike(String value) {
            addCriterion("nome like", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotLike(String value) {
            addCriterion("nome not like", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeIn(List<String> values) {
            addCriterion("nome in", values, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotIn(List<String> values) {
            addCriterion("nome not in", values, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeBetween(String value1, String value2) {
            addCriterion("nome between", value1, value2, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotBetween(String value1, String value2) {
            addCriterion("nome not between", value1, value2, "nome");
            return (Criteria) this;
        }

        public Criteria andPrezzoIsNull() {
            addCriterion("prezzo is null");
            return (Criteria) this;
        }

        public Criteria andPrezzoIsNotNull() {
            addCriterion("prezzo is not null");
            return (Criteria) this;
        }

        public Criteria andPrezzoEqualTo(Integer value) {
            addCriterion("prezzo =", value, "prezzo");
            return (Criteria) this;
        }

        public Criteria andPrezzoNotEqualTo(Integer value) {
            addCriterion("prezzo <>", value, "prezzo");
            return (Criteria) this;
        }

        public Criteria andPrezzoGreaterThan(Integer value) {
            addCriterion("prezzo >", value, "prezzo");
            return (Criteria) this;
        }

        public Criteria andPrezzoGreaterThanOrEqualTo(Integer value) {
            addCriterion("prezzo >=", value, "prezzo");
            return (Criteria) this;
        }

        public Criteria andPrezzoLessThan(Integer value) {
            addCriterion("prezzo <", value, "prezzo");
            return (Criteria) this;
        }

        public Criteria andPrezzoLessThanOrEqualTo(Integer value) {
            addCriterion("prezzo <=", value, "prezzo");
            return (Criteria) this;
        }

        public Criteria andPrezzoIn(List<Integer> values) {
            addCriterion("prezzo in", values, "prezzo");
            return (Criteria) this;
        }

        public Criteria andPrezzoNotIn(List<Integer> values) {
            addCriterion("prezzo not in", values, "prezzo");
            return (Criteria) this;
        }

        public Criteria andPrezzoBetween(Integer value1, Integer value2) {
            addCriterion("prezzo between", value1, value2, "prezzo");
            return (Criteria) this;
        }

        public Criteria andPrezzoNotBetween(Integer value1, Integer value2) {
            addCriterion("prezzo not between", value1, value2, "prezzo");
            return (Criteria) this;
        }

        public Criteria andAutoreIdIsNull() {
            addCriterion("autore_id is null");
            return (Criteria) this;
        }

        public Criteria andAutoreIdIsNotNull() {
            addCriterion("autore_id is not null");
            return (Criteria) this;
        }

        public Criteria andAutoreIdEqualTo(Integer value) {
            addCriterion("autore_id =", value, "autoreId");
            return (Criteria) this;
        }

        public Criteria andAutoreIdNotEqualTo(Integer value) {
            addCriterion("autore_id <>", value, "autoreId");
            return (Criteria) this;
        }

        public Criteria andAutoreIdGreaterThan(Integer value) {
            addCriterion("autore_id >", value, "autoreId");
            return (Criteria) this;
        }

        public Criteria andAutoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("autore_id >=", value, "autoreId");
            return (Criteria) this;
        }

        public Criteria andAutoreIdLessThan(Integer value) {
            addCriterion("autore_id <", value, "autoreId");
            return (Criteria) this;
        }

        public Criteria andAutoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("autore_id <=", value, "autoreId");
            return (Criteria) this;
        }

        public Criteria andAutoreIdIn(List<Integer> values) {
            addCriterion("autore_id in", values, "autoreId");
            return (Criteria) this;
        }

        public Criteria andAutoreIdNotIn(List<Integer> values) {
            addCriterion("autore_id not in", values, "autoreId");
            return (Criteria) this;
        }

        public Criteria andAutoreIdBetween(Integer value1, Integer value2) {
            addCriterion("autore_id between", value1, value2, "autoreId");
            return (Criteria) this;
        }

        public Criteria andAutoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("autore_id not between", value1, value2, "autoreId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table libri
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 06 15:27:41 CET 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table libri
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}