package it.formazione.libreria.mybatis.mapper;

import it.formazione.libreria.mybatis.model.Autori;
import it.formazione.libreria.mybatis.model.AutoriExample;
import java.util.List;

import it.formazione.libreria.mybatis.model.Libri;
import org.apache.ibatis.annotations.Param;

public interface AutoriMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    long countByExample(AutoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int deleteByExample(AutoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int insert(Autori row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int insertSelective(Autori row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    List<Autori> selectByExample(AutoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    Autori selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int updateByExampleSelective(@Param("row") Autori row, @Param("example") AutoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int updateByExample(@Param("row") Autori row, @Param("example") AutoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int updateByPrimaryKeySelective(Autori row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int updateByPrimaryKey(Autori row);


//////////////////////////////////////////MY CODE

    List<Libri> selectAutoriWithLibri(Integer idM, Integer prezzol);


    List<Autori> selectViaAutoriOrLibroOrCasa(Integer autoreID, Integer libroID, Integer casaID);



}