package it.formazione.libreria.mybatis.mapper;

import it.formazione.libreria.mybatis.model.CasaEditrice;
import it.formazione.libreria.mybatis.model.CasaEditriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CasaEditriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 12:32:31 CET 2023
     */
    long countByExample(CasaEditriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 12:32:31 CET 2023
     */
    int deleteByExample(CasaEditriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 12:32:31 CET 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 12:32:31 CET 2023
     */
    int insert(CasaEditrice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 12:32:31 CET 2023
     */
    int insertSelective(CasaEditrice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 12:32:31 CET 2023
     */
    List<CasaEditrice> selectByExample(CasaEditriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 12:32:31 CET 2023
     */
    CasaEditrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 12:32:31 CET 2023
     */
    int updateByExampleSelective(@Param("row") CasaEditrice row, @Param("example") CasaEditriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 12:32:31 CET 2023
     */
    int updateByExample(@Param("row") CasaEditrice row, @Param("example") CasaEditriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 12:32:31 CET 2023
     */
    int updateByPrimaryKeySelective(CasaEditrice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 12:32:31 CET 2023
     */
    int updateByPrimaryKey(CasaEditrice row);
}