package it.formazione.libreria.mybatis.mapper;

import it.formazione.libreria.mybatis.model.CasaEditrice;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface CasaEditriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 17:49:16 CET 2023
     */
    @Delete({
        "delete from casa_editrice",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 17:49:16 CET 2023
     */
    @Insert({
        "insert into casa_editrice (id, nome_casa)",
        "values (#{id,jdbcType=INTEGER}, #{nomeCasa,jdbcType=VARCHAR})"
    })
    int insert(CasaEditrice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 17:49:16 CET 2023
     */
    @Select({
        "select",
        "id, nome_casa",
        "from casa_editrice",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="nome_casa", property="nomeCasa", jdbcType=JdbcType.VARCHAR)
    })
    CasaEditrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 17:49:16 CET 2023
     */
    @Select({
        "select",
        "id, nome_casa",
        "from casa_editrice"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="nome_casa", property="nomeCasa", jdbcType=JdbcType.VARCHAR)
    })
    List<CasaEditrice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table casa_editrice
     *
     * @mbg.generated Tue Nov 07 17:49:16 CET 2023
     */
    @Update({
        "update casa_editrice",
        "set nome_casa = #{nomeCasa,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CasaEditrice row);
}